const Keys = {
    Escape: 0,
    F1: 1,
    F2: 2,
    F3: 3,
    F4: 4,
    F5: 5,
    F6: 6,
    F7: 7,
    F8: 8,
    F9: 9,
    F10: 10,
    F11: 11,
    F12: 12,
    F13: 13,
    F14: 14,
    F15: 15,
    F16: 16,
    F17: 17,
    F18: 18,
    F19: 19,
    F20: 20,
    F21: 21,
    F22: 22,
    F23: 23,
    F24: 24,
    Print: 25,
    ScrollLock: 26,
    Pause: 27,
    Grave: 28,
    Num1: 29,
    Num2: 30,
    Num3: 31,
    Num4: 32,
    Num5: 33,
    Num6: 34,
    Num7: 35,
    Num8: 36,
    Num9: 37,
    Num0: 38,
    Minus: 39,
    Equal: 40,
    Backspace: 41,
    Insert: 42,
    Home: 43,
    PageUp: 44,
    NumLock: 45,
    NumPadEqual: 46,
    Divide: 47,
    Multiply: 48,
    Subtract: 49,
    Tab: 50,
    Q: 51,
    W: 52,
    E: 53,
    R: 54,
    T: 55,
    Y: 56,
    U: 57,
    I: 58,
    O: 59,
    P: 60,
    LeftBracket: 61,
    RightBracket: 62,
    Backslash: 63,
    Delete: 64,
    End: 65,
    PageDown: 66,
    NumPad7: 67,
    NumPad8: 68,
    NumPad9: 69,
    Add: 70,
    CapsLock: 71,
    A: 72,
    S: 73,
    D: 74,
    F: 75,
    G: 76,
    H: 77,
    J: 78,
    K: 79,
    L: 80,
    Semicolon: 81,
    Quote: 82,
    Return: 83,
    NumPad4: 84,
    NumPad5: 85,
    NumPad6: 86,
    LeftShift: 87,
    Z: 88,
    X: 89,
    C: 90,
    V: 91,
    B: 92,
    N: 93,
    M: 94,
    Comma: 95,
    Period: 96,
    Slash: 97,
    RightShift: 98,
    Up: 99,
    NumPad1: 100,
    NumPad2: 101,
    NumPad3: 102,
    Enter: 103,
    LeftControl: 104,
    LeftSuper: 105,
    LeftWin: 106,
    LeftCmd: 107,
    LeftAlt: 108,
    LeftMeta: 109,
    RightControl: 110,
    RightSuper: 111,
    RightWin: 112,
    RightAlt: 113,
    RightCmd: 114,
    RightMeta: 115,
    Space: 116,
    Menu: 117,
    Fn: 118,
    Left: 119,
    Down: 120,
    Right: 121,
    NumPad0: 122,
    Decimal: 123,
    Clear: 124,
    AudioMute: 125,
    AudioVolDown: 126,
    AudioVolUp: 127,
    AudioPlay: 128,
    AudioStop: 129,
    AudioPause: 130,
    AudioPrev: 131,
    AudioNext: 132,
    AudioRewind: 133,
    AudioForward: 134,
    AudioRepeat: 135,
    AudioRandom: 136
};

for (const [key, value] of Object.entries(Keys)) {
    Keys[value] = key;
}


/**
 * @param {number} code 
 * @returns {string}
 */
function getKeyCharByCode(code) {
    const name = Keys[code];
    const map = {
        Num0: "0",
        Num1: "1",
        Num2: "2",
        Num3: "3",
        Num4: "4",
        Num5: "5",
        Num6: "6",
        Num7: "7",
        Num8: "8",
        Num9: "9",
        Q: "Q",
        W: "W",
        E: "E",
        R: "R",
        T: "T",
        Y: "Y",
        U: "U",
        I: "I",
        O: "O",
        P: "P",
        A: "A",
        S: "S",
        D: "D",
        F: "F",
        G: "G",
        H: "H",
        J: "J",
        K: "K",
        L: "L",
        Z: "Z",
        X: "X",
        C: "C",
        V: "V",
        B: "B",
        N: "N",
        M: "M",
        LeftShift: "LeftShift",
        RightShift: "RightShift",
        Escape: "Escape",
        Tab: "Tab",
        CapsLock: "CapsLock",
        Minus: "-",
        Equal: "=",
        Comma: ",",
        Period: ".",
        Slash: "/",
        Semicolon: ";",
        Quote: "'",
        Backslash: "\\",
        Grave: "`",
        Space: " ",
    };

    return map[name];
}

/**
 * @param {string} string 
 * @returns {number}
 */
function getKeyCodeByString(string) {
    string = string.toUpperCase();
    const map = {
        "0": "Num0",
        "1": "Num1",
        "2": "Num2",
        "3": "Num3",
        "4": "Num4",
        "5": "Num5",
        "6": "Num6",
        "7": "Num7",
        "8": "Num8",
        "9": "Num9",
        "Q": "Q",
        "W": "W",
        "E": "E",
        "R": "R",
        "T": "T",
        "Y": "Y",
        "U": "U",
        "I": "I",
        "O": "O",
        "P": "P",
        "A": "A",
        "S": "S",
        "D": "D",
        "F": "F",
        "G": "G",
        "H": "H",
        "J": "J",
        "K": "K",
        "L": "L",
        "Z": "Z",
        "X": "X",
        "C": "C",
        "V": "V",
        "B": "B",
        "N": "N",
        "M": "M",
        "-": "Minus",
        "=": "Equal",
        ",": "Comma",
        ".": "Period",
        "/": "Slash",
        ";": "Semicolon",
        "'": "Quote",
        "\\": "Backslash",
        "`": "Grave",
        " ": "Space"
    };

    const keyName = map[string];
    if (!keyName) return undefined;
    return Keys[keyName];
}


module.exports = { Keys, getKeyCharByCode, getKeyCodeByString };
